// <auto-generated />
namespace ProductManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Socks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Socks));
        
        string IMigrationMetadata.Id
        {
            get { return "201312142250251_Socks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
